package com.hotel.model;

public enum ERole {
    ROLE_USER,
    ROLE_MODERATOR,
    ROLE_ADMIN,
    ROLE_RECEPTIONIST,
    ROLE_ACCOUNTANT,
    ROLE_CLEANER,
    ROLE_BUTLER,
    ROLE_MANAGER,
    ROLE_KITCHEN_MANAGER,
    ROLE_REPAIRMAN,
}